ARG BASE_IMAGE=mixa3607/llama.cpp-gfx906:b10808-rocm-7.14-mxxm-20260826041541-pre

FROM ${BASE_IMAGE} AS build
RUN pip3 install --no-cache-dir cmake
COPY . /build/llamacpp
WORKDIR /build/llamacpp
RUN export HIPCXX="$(hipconfig -l)/clang" && \
    export HIP_PATH="$(hipconfig -R)" && \
    cmake -S . -B build \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLAMA_BUILD_TESTS=OFF \
      -DLLAMA_BUILD_UI=OFF \
      -DLLAMA_USE_PREBUILT_UI=OFF \
      -DLLAMA_OPENSSL=OFF \
      -DGGML_BACKEND_DL=ON \
      -DGGML_HIP=ON \
      -DGGML_HIP_GRAPHS=ON \
      -DGGML_HIP_RCCL=ON \
      -DAMDGPU_TARGETS=gfx906 \
      -DCMAKE_HIP_FLAGS="-mllvm -amdgpu-sched-strategy=max-ilp" \
      -DGGML_RPC=ON \
      -DGGML_CPU_ALL_VARIANTS=ON \
      -DGGML_AVX512=ON \
      -DGGML_AVX512_VBMI=ON \
      -DGGML_AVX512_VNNI=ON \
      -DGGML_AVX512_BF16=ON && \
    cmake --build build --config Release --target llama-server -j"$(nproc)"

FROM ${BASE_IMAGE}
COPY --from=build /build/llamacpp/build/bin/ /app/
